import { yekan } from "@/utils/fonts";

import "./globals.css";
import Header from "@/layout/Header";
import Footer from "@/layout/Footer";

export const metadata = {
  title: "Real State App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={`${yekan.className} container`}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
